spring:
  datasource:
    url: jdbc:mysql://47.101.171.252:3306/zgjm?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: admin
    password: ly19980527

server:
  ssl:
    key-store: keystore.p12
    key-store-password: ly19980527
    keyStoreType: PKCS12
    keyAlias: tomcat
  port: 10443
